import { NextResponse } from "next/server";
import db from "@/lib/db";
import { requireApiRole } from "@/lib/auth";
import { cleanText } from "@/lib/validation";

export async function GET(request:Request){const auth=await requireApiRole();if(auth.response)return auth.response;const target=new URL(request.url).searchParams.get("targetId");if(!target)return NextResponse.json({messages:[]});const allowed=auth.session.role==="owner"?db.prepare("SELECT id FROM users WHERE id=? AND role='buyer'").get(target):db.prepare("SELECT id FROM users WHERE id=? AND role='owner'").get(target);if(!allowed)return NextResponse.json({error:"无权查看此会话"},{status:403});const messages=db.prepare(`SELECT id,from_user_id fromUserId,to_user_id toUserId,order_id orderId,msg_type msgType,content,is_read isRead,created_at createdAt FROM im_message WHERE (from_user_id=? AND to_user_id=?) OR (from_user_id=? AND to_user_id=?) ORDER BY created_at`).all(auth.session.userId,target,target,auth.session.userId);db.prepare("UPDATE im_message SET is_read=1 WHERE to_user_id=? AND from_user_id=?").run(auth.session.userId,target);return NextResponse.json({messages});}

export async function POST(request: Request) {
  const auth=await requireApiRole();if(auth.response)return auth.response;const body=await request.json().catch(()=>({}));let toUserId=String(body.toUserId??"");const content=cleanText(body.content,2000);const msgType=["text","product"].includes(body.msgType)?body.msgType:"text";if(auth.session.role==="buyer"){const owner=db.prepare("SELECT id FROM users WHERE role='owner' AND status='active' LIMIT 1").get() as {id:string}|undefined;if(!owner)return NextResponse.json({error:"商户客服尚未配置"},{status:503});toUserId=owner.id;}else{const buyer=db.prepare("SELECT id FROM users WHERE id=? AND role='buyer' AND status='active'").get(toUserId);if(!buyer)return NextResponse.json({error:"客户不存在"},{status:404});}if(!content)return NextResponse.json({error:"消息内容不能为空"},{status:400});
  const id=db.transaction(()=>{const result=db.prepare(`INSERT INTO im_message(from_user_id,to_user_id,order_id,msg_type,content,is_read) VALUES(?,?,?,?,?,0)`).run(auth.session.userId,toUserId,body.orderId?String(body.orderId):null,msgType,content);db.prepare(`INSERT INTO im_conversation(user_id,target_id,last_msg,unread_count,updated_at) VALUES(?,?,?,0,CURRENT_TIMESTAMP) ON CONFLICT(user_id,target_id) DO UPDATE SET last_msg=excluded.last_msg,updated_at=CURRENT_TIMESTAMP`).run(auth.session.userId,toUserId,content);db.prepare(`INSERT INTO im_conversation(user_id,target_id,last_msg,unread_count,updated_at) VALUES(?,?,?,1,CURRENT_TIMESTAMP) ON CONFLICT(user_id,target_id) DO UPDATE SET last_msg=excluded.last_msg,unread_count=unread_count+1,updated_at=CURRENT_TIMESTAMP`).run(toUserId,auth.session.userId,content);return Number(result.lastInsertRowid);})();return NextResponse.json({id,createdAt:new Date().toISOString()});
}
