import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import db from "@/lib/db";
import { requireApiRole } from "@/lib/auth";
import { cleanText, isPhone, normalizePhone } from "@/lib/validation";
import { refreshProfileCompletion } from "@/lib/customer-profile";

export async function GET(){const auth=await requireApiRole("buyer");if(auth.response)return auth.response;return NextResponse.json({addresses:db.prepare(`SELECT id,recipient_name recipientName,phone,province,city,district,detail,is_default isDefault FROM addresses WHERE user_id=? ORDER BY is_default DESC,created_at DESC`).all(auth.session.userId)},{headers:{"Cache-Control":"no-store"}});}
export async function POST(request:Request){const auth=await requireApiRole("buyer");if(auth.response)return auth.response;const body=await request.json().catch(()=>({}));const data={recipientName:cleanText(body.recipientName,40),phone:normalizePhone(body.phone),province:cleanText(body.province,30),city:cleanText(body.city,30),district:cleanText(body.district,30),detail:cleanText(body.detail,120)};if(!data.recipientName||!isPhone(data.phone)||!data.province||!data.city||!data.district||!data.detail)return NextResponse.json({error:"请完整填写收货信息"},{status:400});const id=randomUUID();db.transaction(()=>{const count=(db.prepare("SELECT COUNT(*) count FROM addresses WHERE user_id=?").get(auth.session.userId)as{count:number}).count,isDefault=Boolean(body.isDefault)||count===0;if(isDefault)db.prepare("UPDATE addresses SET is_default=0 WHERE user_id=?").run(auth.session.userId);db.prepare(`INSERT INTO addresses(id,user_id,recipient_name,phone,province,city,district,detail,is_default) VALUES(?,?,?,?,?,?,?,?,?)`).run(id,auth.session.userId,data.recipientName,data.phone,data.province,data.city,data.district,data.detail,isDefault?1:0);refreshProfileCompletion(auth.session.userId);})();return NextResponse.json({id,profileCompleted:refreshProfileCompletion(auth.session.userId)},{status:201});}
