import {NextResponse}from"next/server";
import db from"@/lib/db";
import{requireApiRole}from"@/lib/auth";
import{cleanText,isPhone,normalizePhone}from"@/lib/validation";
import{refreshProfileCompletion}from"@/lib/customer-profile";

const addressData=(body:Record<string,unknown>)=>({recipientName:cleanText(body.recipientName,40),phone:normalizePhone(body.phone),province:cleanText(body.province,30),city:cleanText(body.city,30),district:cleanText(body.district,30),detail:cleanText(body.detail,120)});
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireApiRole("buyer");if(auth.response)return auth.response;const{id}=await params,body=await request.json().catch(()=>({}))as Record<string,unknown>,data=addressData(body);if(!data.recipientName||!isPhone(data.phone)||!data.province||!data.city||!data.district||!data.detail)return NextResponse.json({error:"请完整填写收货信息"},{status:400});const result=db.transaction(()=>{const exists=db.prepare("SELECT id FROM addresses WHERE id=? AND user_id=?").get(id,auth.session.userId);if(!exists)return 0;if(body.isDefault)db.prepare("UPDATE addresses SET is_default=0 WHERE user_id=?").run(auth.session.userId);return db.prepare("UPDATE addresses SET recipient_name=?,phone=?,province=?,city=?,district=?,detail=?,is_default=CASE WHEN ? THEN 1 ELSE is_default END WHERE id=? AND user_id=?").run(data.recipientName,data.phone,data.province,data.city,data.district,data.detail,body.isDefault?1:0,id,auth.session.userId).changes;})();if(!result)return NextResponse.json({error:"地址不存在"},{status:404});refreshProfileCompletion(auth.session.userId);return NextResponse.json({ok:true});}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireApiRole("buyer");if(auth.response)return auth.response;const{id}=await params;const result=db.transaction(()=>{const row=db.prepare("SELECT is_default isDefault FROM addresses WHERE id=? AND user_id=?").get(id,auth.session.userId)as{isDefault:number}|undefined;if(!row)return 0;db.prepare("DELETE FROM addresses WHERE id=? AND user_id=?").run(id,auth.session.userId);if(row.isDefault)db.prepare("UPDATE addresses SET is_default=1 WHERE id=(SELECT id FROM addresses WHERE user_id=? ORDER BY created_at DESC LIMIT 1)").run(auth.session.userId);return 1;})();if(!result)return NextResponse.json({error:"地址不存在"},{status:404});return NextResponse.json({ok:true,profileCompleted:refreshProfileCompletion(auth.session.userId)});}
