import { randomUUID } from "node:crypto";
import db from "@/lib/db";
import { cleanText } from "@/lib/validation";

export type NoticeMark = { bold?: boolean; italic?: boolean; underline?: boolean; fontSize?: 12|14|16|18|20|24|28|32; color?: string; link?: string };
export type NoticeBlock = { type:"heading"|"paragraph"|"list"|"image"; text?:string; items?:string[]; level?:1|2|3; align?:"left"|"center"|"right"; marks?:NoticeMark; src?:string; alt?:string };
export type NoticeDocument = { blocks: NoticeBlock[] };
const COLORS = new Set(["#0f172a","#475569","#c2410c","#dc2626","#047857","#1d4ed8","#7e22ce"]);
const SIZES = new Set([12,14,16,18,20,24,28,32]);
function safeUrl(value:unknown,image=false){const text=cleanText(value,500);if(!text)return "";if(image&&text.startsWith("/api/"))return text;try{const url=new URL(text);return ["https:",...(image?[]:["mailto:"])].includes(url.protocol)?url.toString():""}catch{return ""}}
export function parseNoticeDocument(input:unknown):NoticeDocument{
 const raw=(input&&typeof input==="object"&&Array.isArray((input as {blocks?:unknown}).blocks))?(input as {blocks:unknown[]}).blocks:[];
 if(!raw.length||raw.length>80)throw new Error("NOTICE_DOCUMENT_INVALID");
 const blocks:NoticeBlock[]=raw.map(item=>{if(!item||typeof item!=="object")throw new Error("NOTICE_DOCUMENT_INVALID");const value=item as Record<string,unknown>,type=value.type;if(!["heading","paragraph","list","image"].includes(String(type)))throw new Error("NOTICE_DOCUMENT_INVALID");const align=["left","center","right"].includes(String(value.align))?value.align as NoticeBlock["align"]:"left";if(type==="image"){const src=safeUrl(value.src,true);if(!src)throw new Error("NOTICE_IMAGE_INVALID");return{type:"image",src,alt:cleanText(value.alt,120),align}}if(type==="list"){const items=Array.isArray(value.items)?value.items.map(x=>cleanText(x,300)).filter(Boolean).slice(0,30):[];if(!items.length)throw new Error("NOTICE_DOCUMENT_INVALID");return{type:"list",items,align}}const text=cleanText(value.text,2000);if(!text)throw new Error("NOTICE_DOCUMENT_INVALID");const markRaw=value.marks&&typeof value.marks==="object"?value.marks as Record<string,unknown>:{};const link=safeUrl(markRaw.link);const marks:NoticeMark={bold:Boolean(markRaw.bold),italic:Boolean(markRaw.italic),underline:Boolean(markRaw.underline),...(SIZES.has(Number(markRaw.fontSize))?{fontSize:Number(markRaw.fontSize) as NoticeMark["fontSize"]}:{}),...(COLORS.has(String(markRaw.color))?{color:String(markRaw.color)}:{}),...(link?{link}:{})};return{type:type as "heading"|"paragraph",text,level:type==="heading"&&[1,2,3].includes(Number(value.level))?Number(value.level) as 1|2|3:undefined,align,marks}});
 if(JSON.stringify(blocks).length>50000)throw new Error("NOTICE_DOCUMENT_TOO_LARGE");return{blocks};
}
const row=(value:Record<string,unknown>)=>({...value,document:JSON.parse(String(value.documentJson)) as NoticeDocument});
export function listAdminNotices(){return (db.prepare("SELECT id,title,document_json documentJson,status,published_at publishedAt,created_at createdAt,updated_at updatedAt FROM customer_notices ORDER BY updated_at DESC").all() as Record<string,unknown>[]).map(row)}
export function listPublishedNotices(){return (db.prepare("SELECT id,title,document_json documentJson,published_at publishedAt,updated_at updatedAt FROM customer_notices WHERE status='published' ORDER BY published_at DESC LIMIT 20").all() as Record<string,unknown>[]).map(row)}
export function saveNotice(input:{id?:string;title:unknown;document:unknown;status?:unknown;idempotencyKey?:unknown;createdBy:string}){const title=cleanText(input.title,120),document=parseNoticeDocument(input.document),status=["draft","published","offline"].includes(String(input.status))?String(input.status):"draft";if(!title)throw new Error("NOTICE_TITLE_REQUIRED");const id=cleanText(input.id,100)||randomUUID(),key=cleanText(input.idempotencyKey,100)||null;db.prepare(`INSERT INTO customer_notices(id,title,document_json,status,idempotency_key,published_at,created_by) VALUES(?,?,?,?,?,CASE WHEN ?='published' THEN CURRENT_TIMESTAMP END,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,document_json=excluded.document_json,status=excluded.status,published_at=CASE WHEN excluded.status='published' THEN COALESCE(customer_notices.published_at,CURRENT_TIMESTAMP) ELSE customer_notices.published_at END,updated_at=CURRENT_TIMESTAMP`).run(id,title,JSON.stringify(document),status,key,status,input.createdBy);return{id,title,document,status}}
export function setNoticeStatus(id:string,status:"published"|"offline"){const result=db.prepare("UPDATE customer_notices SET status=?,published_at=CASE WHEN ?='published' THEN COALESCE(published_at,CURRENT_TIMESTAMP) ELSE published_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,status,id);if(!result.changes)throw new Error("NOTICE_NOT_FOUND")}
