import db from '@/lib/db';
import { createOrderRevision } from './order-revisions';
import { buyerConfirm, cancelOrder, merchantConfirm } from './order-lifecycle';
type Row = { id:string; status:string; buyerUserId:string; orderNo:string; orderVersion:number; merchantConfirmedVersion:number; buyerConfirmedVersion:number; confirmationStatus:any; fulfillmentStatus:any };
export function getLifecycleOrder(orderId:string): Row {
  const row = db.prepare('SELECT id,status,buyer_user_id buyerUserId,order_no orderNo,order_version orderVersion,merchant_confirmed_version merchantConfirmedVersion,buyer_confirmed_version buyerConfirmedVersion,confirmation_status confirmationStatus,fulfillment_status fulfillmentStatus FROM orders WHERE id=? AND deleted_at IS NULL').get(orderId) as Row|undefined;
  if (!row) throw new Error('NOT_FOUND'); return row;
}
export function withdrawOrder(orderId:string, actorUserId:string) { return db.transaction(() => { const order=getLifecycleOrder(orderId); if(order.buyerUserId!==actorUserId) throw new Error('FORBIDDEN'); if(order.confirmationStatus==='cancelled'||['shipped','closed','cancelled'].includes(order.status)) throw new Error('LOCKED'); const version=createOrderRevision(db,{orderId,actorUserId,reason:'customer-withdraw'}); db.prepare("UPDATE orders SET status='pending_review',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(orderId); return {version}; })(); }
export function cancelCustomerOrder(orderId:string, actorUserId:string) { return db.transaction(() => { const order=getLifecycleOrder(orderId); if(order.buyerUserId!==actorUserId) throw new Error('FORBIDDEN'); cancelOrder(order); db.prepare("UPDATE orders SET status='cancelled',confirmation_status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(orderId); return {ok:true}; })(); }
export function hideCustomerOrder(orderId:string, actorUserId:string) { const order=getLifecycleOrder(orderId); if(order.buyerUserId!==actorUserId) throw new Error('FORBIDDEN'); db.prepare('UPDATE orders SET customer_hidden_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(orderId); return {ok:true}; }
export function confirmByMerchant(orderId:string, version:number) { return db.transaction(() => { const order=getLifecycleOrder(orderId); const next=merchantConfirm(order,version); db.prepare("UPDATE orders SET confirmation_status='buyer_review',merchant_confirmed_version=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND order_version=?").run(next.merchantConfirmedVersion,orderId,version); return next; })(); }
export function confirmByBuyer(orderId:string, actorUserId:string, version:number) { return db.transaction(() => { const order=getLifecycleOrder(orderId); if(order.buyerUserId!==actorUserId) throw new Error('FORBIDDEN'); const next=buyerConfirm(order,version); db.prepare("UPDATE orders SET confirmation_status='confirmed',buyer_confirmed_version=?,confirmed_quote_version=?,status='pending_payment',updated_at=CURRENT_TIMESTAMP WHERE id=? AND order_version=?").run(next.buyerConfirmedVersion,version,orderId,version); return next; })(); }
