import {NextResponse}from"next/server";
import db from"@/lib/db";
import{requireApiRole}from"@/lib/auth";
import{buyerProfile,refreshProfileCompletion}from"@/lib/customer-profile";
import{cleanText}from"@/lib/validation";

export async function GET(){const auth=await requireApiRole("buyer");if(auth.response)return auth.response;return NextResponse.json({profile:buyerProfile(auth.session.userId)},{headers:{"Cache-Control":"no-store"}});}
function tableColumns(table:string){return new Set((db.prepare(`PRAGMA table_info(${table})`).all() as Array<{name:string}>).map(column=>column.name));}
export async function PATCH(request:Request){const auth=await requireApiRole("buyer");if(auth.response)return auth.response;const body=await request.json().catch(()=>({})),displayName=cleanText(body.displayName,60),shopName=cleanText(body.shopName,100),businessType=cleanText(body.businessType,60);if(!displayName||!shopName)return NextResponse.json({error:"请填写客户姓名和店名"},{status:400});try{db.transaction(()=>{const userColumns=tableColumns("users"),profileColumns=tableColumns("customer_profile");db.prepare(userColumns.has("updated_at")?"UPDATE users SET display_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?":"UPDATE users SET display_name=? WHERE id=?").run(displayName,auth.session.userId);const profileUpdate=profileColumns.has("updated_at")?"shop_name=excluded.shop_name,business_type=excluded.business_type,updated_at=CURRENT_TIMESTAMP":"shop_name=excluded.shop_name,business_type=excluded.business_type";db.prepare(`INSERT INTO customer_profile(user_id,shop_name,business_type) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET ${profileUpdate}`).run(auth.session.userId,shopName,businessType||null);})();const profileCompleted=refreshProfileCompletion(auth.session.userId);return NextResponse.json({ok:true,profileCompleted,profile:buyerProfile(auth.session.userId)});}catch(error){console.error("customer profile update failed",{reason:error instanceof Error?error.message.slice(0,160):"UNKNOWN"});return NextResponse.json({error:"资料暂时无法保存，请刷新后重试"},{status:503});}}
