import { NextResponse } from "next/server";
import db from "@/lib/db";
import { requireApiRole } from "@/lib/auth";
import { cleanText } from "@/lib/validation";
import { writeAudit } from "@/lib/audit";
import { requestIp } from "@/lib/security";

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireApiRole("owner");if(auth.response)return auth.response;const{id}=await params;const customer=db.prepare(`SELECT u.id,u.display_name displayName,u.phone,u.status,u.created_at createdAt,p.shop_name shopName,p.shop_address shopAddress,p.business_type businessType,p.customer_level customerLevel,p.receive_preference receivePreference,p.brand_preference brandPreference,p.internal_remark internalRemark,p.birthday,p.anniversary FROM users u LEFT JOIN customer_profile p ON p.user_id=u.id WHERE u.id=? AND u.role='buyer'`).get(id);if(!customer)return NextResponse.json({error:"客户不存在"},{status:404});const addresses=db.prepare("SELECT id,recipient_name recipientName,phone,province,city,district,detail,is_default isDefault,created_at createdAt FROM addresses WHERE user_id=? ORDER BY is_default DESC,created_at DESC").all(id);const orders=db.prepare("SELECT id,order_no orderNo,status,total_amount totalAmount,created_at createdAt,closed_at closedAt FROM orders WHERE buyer_user_id=? AND deleted_at IS NULL ORDER BY created_at DESC").all(id);return NextResponse.json({customer,addresses,orders},{headers:{"Cache-Control":"no-store"}});}

export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireApiRole("owner");if(auth.response)return auth.response;const{id}=await params,body=await request.json().catch(()=>({}));const existing=db.prepare("SELECT id FROM users WHERE id=? AND role='buyer'").get(id);if(!existing)return NextResponse.json({error:"客户不存在"},{status:404});const status=body.status==="disabled"?"disabled":"active";const data={displayName:cleanText(body.displayName,60),shopName:cleanText(body.shopName,100),shopAddress:cleanText(body.shopAddress,200),businessType:cleanText(body.businessType,60),customerLevel:cleanText(body.customerLevel,40)||"普通客户",internalRemark:cleanText(body.internalRemark,500)};db.transaction(()=>{db.prepare("UPDATE users SET display_name=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(data.displayName||null,status,id);db.prepare(`INSERT INTO customer_profile(user_id,shop_name,shop_address,business_type,customer_level,internal_remark) VALUES(?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET shop_name=excluded.shop_name,shop_address=excluded.shop_address,business_type=excluded.business_type,customer_level=excluded.customer_level,internal_remark=excluded.internal_remark,updated_at=CURRENT_TIMESTAMP`).run(id,data.shopName||null,data.shopAddress||null,data.businessType||null,data.customerLevel,data.internalRemark||null);if(status==="disabled")db.prepare("UPDATE auth_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND revoked_at IS NULL").run(id);})();writeAudit({actorUserId:auth.session.userId,actorRole:"owner",action:"customer.updated",objectType:"user",objectId:id,ip:requestIp(request),metadata:{status,customerLevel:data.customerLevel}});return NextResponse.json({ok:true});}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireApiRole("owner");if(auth.response)return auth.response;const{id}=await params;const result=db.transaction(()=>{const changed=db.prepare("UPDATE users SET status='disabled',updated_at=CURRENT_TIMESTAMP WHERE id=? AND role='buyer' AND status!='disabled'").run(id);if(changed.changes)db.prepare("UPDATE auth_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=? AND revoked_at IS NULL").run(id);return changed.changes;})();if(!result)return NextResponse.json({error:"客户不存在或已停用"},{status:404});writeAudit({actorUserId:auth.session.userId,actorRole:"owner",action:"customer.disabled",objectType:"user",objectId:id,ip:requestIp(request)});return NextResponse.json({ok:true});}
