"use client";

import Image from "next/image";
import Link from "next/link";
import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { Archive, ChevronDown, ChevronUp, ImagePlus, PackagePlus, Pencil, Search, Star, Trash2, X } from "lucide-react";

type Tier={minQty:number;maxQty:number|null;unitPrice:number};
type Sku={id?:string;skuCode:string;specName:string;basePrice:number;warehouseBasePrice?:number|null;salePriceOverride?:number|null;stock:number;tiers:Tier[];warehouseVariantId?:string|null;archivedAt?:string|null};
type ProductImage={id:string;url:string;isPrimary:boolean;sortOrder:number;byteSize:number};
type Product={id:string;name:string;category:string;brand:string;description:string;status:"active"|"inactive";warehouseProductId?:string|null;warehouseRevision?:number|null;archived:boolean;images:ProductImage[];primaryImage:ProductImage|null;skus:Sku[];totalStock:number;recommendationIds?:string[]};
const emptySku=():Sku=>({skuCode:"",specName:"",basePrice:0,stock:0,tiers:[]});
const emptyProduct=():Product=>({id:"",name:"",category:"",brand:"",description:"",status:"inactive",archived:false,images:[],primaryImage:null,skus:[emptySku()],totalStock:0});

export default function ProductManager(){const[products,setProducts]=useState<Product[]>([]);const[query,setQuery]=useState("");const[category,setCategory]=useState("all");const[status,setStatus]=useState("all");const[editing,setEditing]=useState<Product|null>(null);const[dirty,setDirty]=useState(false);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 const load=async()=>{const r=await fetch("/api/products",{cache:"no-store"});const j=await r.json();setProducts(j.products||[]);};useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[]);
 const categories=useMemo(()=>[...new Set(products.filter(p=>!p.archived).map(p=>p.category))],[products]);const filtered=products.filter(p=>!p.archived&&(!query||`${p.name} ${p.brand} ${p.skus.map(s=>s.skuCode).join(" ")}`.toLowerCase().includes(query.toLowerCase()))&&(category==="all"||p.category===category)&&(status==="all"||p.status===status));
 const open=(product?:Product)=>{setEditing(product?structuredClone(product):emptyProduct());setDirty(false);setNotice("")};const close=()=>{if(dirty&&!window.confirm("还有未保存内容，确定关闭吗？"))return;setEditing(null);setDirty(false)};
 const changeStatus=async(product:Product,next:"active"|"inactive")=>{if(product.warehouseProductId)return setNotice("仓库同步商品的上下架状态由仓库管理");const r=await fetch(`/api/products/${product.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"status",status:next})});const j=await r.json();setNotice(r.ok?next==="active"?"商品已上架":"商品已下架":j.error);await load()};
 const archive=async(product:Product)=>{if(!window.confirm(`归档“${product.name}”后客户将无法购买，确定继续吗？`))return;const r=await fetch(`/api/products/${product.id}`,{method:"DELETE"});const j=await r.json();setNotice(r.ok?"商品已归档":j.error);await load()};
 const remove=async(product:Product)=>{if(!window.confirm(`确定处理未上架商品“${product.name}”吗？符合安全条件时会永久删除，否则会自动归档。`))return;const r=await fetch(`/api/products/${product.id}`,{method:"DELETE"}),j=await r.json().catch(()=>({}));const resultLabel=j.action==="deleted"?"已永久删除":j.action==="archived"?"已自动归档":"商品已处理";setNotice(r.ok?`${resultLabel}：${j.reason||"处理完成"}`:(j.error||"商品处理失败"));await load()};
 return <div><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold">商品管理</h2><p className="mt-1 text-sm text-slate-500">维护商品图片、规格、阶梯价、库存与销售状态</p></div><button onClick={()=>open()} className="flex items-center justify-center gap-2 rounded-xl bg-orange-500 px-4 py-3 text-sm font-semibold text-white"><PackagePlus size={17}/>新增商品</button></div>{notice&&<button onClick={()=>setNotice("")} className="mt-4 w-full rounded-xl bg-emerald-50 px-4 py-3 text-left text-sm text-emerald-700">{notice}</button>}
  <div className="mt-5 flex flex-col gap-3 md:flex-row"><label className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索商品、品牌或 SKU" className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-3 text-sm"/></label><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-slate-200 px-3 text-sm"><option value="all">全部分类</option>{categories.map(item=><option key={item}>{item}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 px-3 text-sm"><option value="all">全部状态</option><option value="active">已上架</option><option value="inactive">已下架</option></select><Link href="/admin/products/archived" className="rounded-xl bg-slate-100 px-4 py-3 text-center text-sm font-semibold">归档商品</Link></div>
 <div className="mt-5 overflow-x-auto"><table className="admin-responsive-table w-full text-left text-sm"><thead className="border-b text-slate-400"><tr><th className="p-3">商品</th><th>分类</th><th>规格</th><th>总库存</th><th>状态</th><th>操作</th></tr></thead><tbody>{filtered.map(product=><tr key={product.id} className="border-b last:border-0"><td data-label="商品" className="p-3"><Link href={`/buyer/products/${product.id}?from=admin`} className="flex items-center gap-3">{product.primaryImage?<Image src={product.primaryImage.url} alt="" width={56} height={56} unoptimized className="h-14 w-14 rounded-xl object-cover"/>:<div className="grid h-14 w-14 place-items-center rounded-xl bg-slate-100 text-xs text-slate-400">无图</div>}<span><b>{product.name}</b><p className="mt-1 text-xs text-slate-400">{product.brand||"未设置品牌"}</p>{product.warehouseProductId&&<p className="mt-1 text-xs font-medium text-sky-700">仓库同步 · 主数据只读</p>}</span></Link></td><td data-label="分类">{product.category}</td><td data-label="规格">{product.skus.filter(s=>!s.archivedAt).length} 个</td><td data-label="总库存">{product.totalStock}</td><td data-label="状态"><span className={`rounded-full px-2 py-1 text-xs ${product.status==="active"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{product.status==="active"?"已上架":"已下架"}</span></td><td data-label="操作"><div className="flex gap-2"><button onClick={()=>open(product)} className="rounded-lg bg-slate-100 p-2" title="编辑"><Pencil size={15}/></button>{!product.warehouseProductId&&<button onClick={()=>changeStatus(product,product.status==="active"?"inactive":"active")} className="rounded-lg bg-orange-50 px-2 py-1 text-xs text-orange-700">{product.status==="active"?"下架":"上架"}</button>}{product.status==="inactive"&&!product.warehouseProductId&&<button onClick={()=>remove(product)} className="rounded-lg bg-red-50 p-2 text-red-600" title="删除未上架商品"><Trash2 size={15}/></button>}{product.status==="active"&&<button onClick={()=>archive(product)} className="rounded-lg bg-slate-100 p-2 text-slate-500" title="归档"><Archive size={15}/></button>}</div></td></tr>)}</tbody></table>{!filtered.length&&<p className="py-12 text-center text-slate-400">没有符合条件的商品</p>}</div>
 {editing&&<Editor product={editing} candidates={products.filter(item=>item.id!==editing.id&&item.status==="active"&&!item.archived&&item.skus.some(sku=>!sku.archivedAt))} setProduct={value=>{setEditing(value);setDirty(true)}} close={close} saved={async(id)=>{await load();const fresh=await fetch(`/api/products/${id}`).then(r=>r.json());setEditing(fresh.product||null);setDirty(false);setNotice("商品已保存")}} busy={busy} setBusy={setBusy} setNotice={setNotice}/>}</div>}

function Editor({product,candidates,setProduct,close,saved,busy,setBusy,setNotice}:{product:Product;candidates:Product[];setProduct:(p:Product)=>void;close:()=>void;saved:(id:string)=>void;busy:boolean;setBusy:(v:boolean)=>void;setNotice:(v:string)=>void}){
 const warehouse=Boolean(product.warehouseProductId);
 const set=<K extends keyof Product>(key:K,value:Product[K])=>setProduct({...product,[key]:value});
 const activeSkus=product.skus.filter(s=>!s.archivedAt);
 const selectedIds=(product.recommendationIds||[]).filter(id=>candidates.some(item=>item.id===id)).slice(0,6);
 const candidateById=new Map(candidates.map(item=>[item.id,item]));
 const save=async()=>{setBusy(true);const payload=warehouse?{action:"merchant-content",description:product.description}:{name:product.name,category:product.category,brand:product.brand,description:product.description,status:product.status,skus:activeSkus};const r=await fetch(product.id?`/api/products/${product.id}`:"/api/products",{method:product.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setNotice(j.error||"保存失败");await saved(j.id||product.id)};
 const updateSku=(index:number,value:Sku)=>set("skus",activeSkus.map((sku,i)=>i===index?value:sku));
 const upload=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value="";if(!file||!product.id||warehouse)return;setBusy(true);const form=new FormData();form.set("file",file);const r=await fetch(`/api/products/${product.id}/images`,{method:"POST",body:form});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setNotice(j.error||"图片上传失败");await saved(product.id)};
 const reorder=async(images:ProductImage[],primaryId?:string)=>{if(warehouse)return;const r=await fetch(`/api/products/${product.id}/images`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderedIds:images.map(i=>i.id),primaryId:primaryId||images.find(i=>i.isPrimary)?.id||images[0]?.id})});const j=await r.json().catch(()=>({}));if(!r.ok)return setNotice(j.error||"图片调整失败");await saved(product.id)};
 const moveImage=(index:number,direction:-1|1)=>{const next=[...product.images],target=index+direction;if(warehouse||target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];void reorder(next)};
 const removeImage=async(image:ProductImage)=>{if(warehouse||!window.confirm("确定删除这张图片吗？"))return;const r=await fetch(`/api/products/${product.id}/images/${image.id}`,{method:"DELETE"});const j=await r.json().catch(()=>({}));if(!r.ok)return setNotice(j.error||"图片删除失败");await saved(product.id)};
 const toggleRecommendation=(id:string)=>{if(selectedIds.includes(id))return set("recommendationIds",selectedIds.filter(item=>item!==id));if(selectedIds.length>=6)return setNotice("最多只能推荐 6 件商品");set("recommendationIds",[...selectedIds,id])};
 const moveRecommendation=(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=selectedIds.length)return;const next=[...selectedIds];[next[index],next[target]]=[next[target],next[index]];set("recommendationIds",next)};
 const saveRecommendations=async()=>{if(!product.id)return setNotice("请先保存商品，再设置推荐商品");setBusy(true);const r=await fetch(`/api/admin/products/${product.id}/recommendations`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({productIds:selectedIds})});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setNotice(j.error||"推荐商品保存失败");set("recommendationIds",j.recommendationIds||selectedIds);setNotice("推荐商品已保存")};
 const saveWarehousePrice=async(sku:Sku,restore=false)=>{if(!product.id||!sku.id||!sku.warehouseVariantId)return;const value=sku.salePriceOverride;if(!restore&&(value===null||value===undefined||!Number.isFinite(value)||value<0))return setNotice("请输入有效的销售覆盖价");setBusy(true);const r=await fetch(`/api/admin/products/${product.id}/skus/${sku.id}/sale-price`,{method:restore?"DELETE":"PUT",headers:{"Content-Type":"application/json"},body:restore?undefined:JSON.stringify({salePriceOverride:value})});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setNotice(j.error||"销售价保存失败");updateSku(activeSkus.findIndex(item=>item.id===sku.id),{...sku,...j.sku});setNotice(restore?"已恢复仓库基准价":"销售覆盖价已保存")};
 return <div className="fixed inset-0 z-[120] bg-slate-950/45" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="mobile-scroll ml-auto h-full w-full max-w-3xl overflow-y-auto bg-white pb-[env(safe-area-inset-bottom)] shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4"><div><h2 className="text-lg font-bold">{product.id?"编辑商品":"新增商品"}</h2><p className="text-xs text-slate-400">{warehouse?"仓库主数据只读；可维护商品说明、销售覆盖价和推荐商品":"维护基本信息、图片、规格、阶梯价与推荐商品"}</p></div><button onClick={close} className="rounded-lg bg-slate-100 p-2"><X size={18}/></button></header><div className="space-y-6 p-5">
 <section className="rounded-2xl border p-4"><h3 className="font-semibold">基本信息</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="商品名称"><input value={product.name} disabled={warehouse} onChange={e=>set("name",e.target.value)} className="input disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500"/></Field><Field label="分类"><input value={product.category} disabled={warehouse} onChange={e=>set("category",e.target.value)} className="input disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500"/></Field><Field label="品牌"><input value={product.brand||""} disabled={warehouse} onChange={e=>set("brand",e.target.value)} className="input disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500"/></Field><Field label="状态"><select value={product.status} disabled={warehouse} onChange={e=>set("status",e.target.value as Product["status"])} className="input disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-500"><option value="inactive">下架</option><option value="active">上架</option></select></Field></div><Field label="商品说明"><textarea value={product.description||""} onChange={e=>set("description",e.target.value)} rows={4} className="input mt-2"/></Field></section>
 <section className="rounded-2xl border p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">商品图片</h3><p className="mt-1 text-xs text-slate-400">{warehouse?"图片由仓库系统同步，此处仅查看":"最多 8 张，单图 5MB，可排序并设置主图"}</p></div>{product.id&&!warehouse&&<label className="flex cursor-pointer items-center gap-2 rounded-xl bg-orange-50 px-3 py-2 text-sm font-semibold text-orange-700"><ImagePlus size={16}/>上传<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload} className="hidden"/></label>}</div>{!product.id?<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-700">请先保存商品基本信息，再上传图片。</p>:<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{product.images.map((image,index)=><div key={image.id} className="relative rounded-xl border p-2"><Image src={image.url} alt="商品图" width={180} height={140} unoptimized className="h-28 w-full rounded-lg object-cover"/>{image.isPrimary&&<span className="absolute left-3 top-3 rounded bg-orange-500 px-2 py-1 text-[10px] text-white">主图</span>}{!warehouse&&<div className="mt-2 grid grid-cols-4 gap-1"><button onClick={()=>moveImage(index,-1)} className="rounded bg-slate-100 p-1"><ChevronUp size={14}/></button><button onClick={()=>moveImage(index,1)} className="rounded bg-slate-100 p-1"><ChevronDown size={14}/></button><button onClick={()=>reorder(product.images,image.id)} className="rounded bg-amber-50 p-1 text-amber-600"><Star size={14}/></button><button onClick={()=>removeImage(image)} className="rounded bg-red-50 p-1 text-red-600"><Trash2 size={14}/></button></div>}</div>)}</div>}</section>
 <section className="rounded-2xl border p-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">规格与阶梯价</h3><p className="mt-1 text-xs text-slate-400">{warehouse?"SKU、规格、库存、仓库基准价和阶梯价只读；仅销售覆盖价可修改":"每个规格独立编码、价格、库存与阶梯价"}</p></div>{!warehouse&&<button onClick={()=>set("skus",[...activeSkus,emptySku()])} className="rounded-xl bg-slate-950 px-3 py-2 text-sm font-semibold text-white">新增规格</button>}</div><div className="mt-4 space-y-4">{activeSkus.map((sku,index)=><SkuEditor key={sku.id||index} sku={sku} warehouse={warehouse} busy={busy} update={value=>updateSku(index,value)} savePrice={saveWarehousePrice} remove={()=>activeSkus.length>1&&set("skus",activeSkus.filter((_,i)=>i!==index))}/>)}</div></section>
 <section className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">推荐商品</h3><p className="mt-1 text-xs text-slate-400">仅可选择当前在售且有有效 SKU 的商品，最多 6 件</p></div><button disabled={busy||!product.id} onClick={saveRecommendations} className="rounded-xl bg-orange-500 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">保存推荐</button></div>{selectedIds.length>0&&<div className="mt-4 space-y-2">{selectedIds.map((id,index)=>{const item=candidateById.get(id);return item?<div key={id} className="flex min-w-0 items-center gap-3 rounded-xl bg-orange-50 p-3"><span className="min-w-0 flex-1 truncate text-sm font-medium">{index+1}. {item.name}</span><button disabled={index===0} onClick={()=>moveRecommendation(index,-1)} className="rounded bg-white p-2 disabled:opacity-30" title="上移"><ChevronUp size={14}/></button><button disabled={index===selectedIds.length-1} onClick={()=>moveRecommendation(index,1)} className="rounded bg-white p-2 disabled:opacity-30" title="下移"><ChevronDown size={14}/></button><button onClick={()=>toggleRecommendation(id)} className="rounded bg-white p-2 text-red-500" title="移除"><X size={14}/></button></div>:null})}</div>}<div className="mt-4 grid max-h-64 gap-2 overflow-y-auto sm:grid-cols-2">{candidates.map(item=>{const checked=selectedIds.includes(item.id);return <label key={item.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 ${checked?"border-orange-300 bg-orange-50":"border-slate-200"}`}><input type="checkbox" checked={checked} onChange={()=>toggleRecommendation(item.id)}/><span className="min-w-0"><b className="block truncate text-sm">{item.name}</b><small className="text-slate-400">{item.category} · {item.skus.filter(sku=>!sku.archivedAt).length} 个规格</small></span></label>})}{!candidates.length&&<p className="text-sm text-slate-400">暂无其他可推荐的在售商品</p>}</div></section>
 </div><footer className="sticky bottom-0 flex flex-wrap justify-end gap-3 border-t bg-white p-4 pb-[max(1rem,env(safe-area-inset-bottom))]"><button onClick={close} className="rounded-xl border px-5 py-3 text-sm">取消</button><button disabled={busy} onClick={save} className="rounded-xl bg-orange-500 px-6 py-3 text-sm font-semibold text-white disabled:opacity-60">{busy?"正在保存…":"保存商品"}</button></footer></aside></div>
}
function SkuEditor({sku,warehouse,busy,update,savePrice,remove}:{sku:Sku;warehouse:boolean;busy:boolean;update:(s:Sku)=>void;savePrice:(s:Sku,restore?:boolean)=>void;remove:()=>void}){
 const set=<K extends keyof Sku>(key:K,value:Sku[K])=>update({...sku,[key]:value});
 if(warehouse)return <div className="rounded-xl bg-slate-50 p-4"><div className="grid gap-3 md:grid-cols-4"><Field label="SKU 编码"><input value={sku.skuCode} disabled className="input cursor-not-allowed bg-slate-100 text-slate-500"/></Field><Field label="规格名称"><input value={sku.specName} disabled className="input cursor-not-allowed bg-slate-100 text-slate-500"/></Field><Field label="仓库基准价"><input value={Number(sku.warehouseBasePrice??sku.basePrice).toFixed(2)} disabled className="input cursor-not-allowed bg-slate-100 text-slate-500"/></Field><Field label="仓库库存"><input value={sku.stock} disabled className="input cursor-not-allowed bg-slate-100 text-slate-500"/></Field></div><div className="mt-4 flex flex-col gap-3 rounded-xl border border-sky-100 bg-white p-3 sm:flex-row sm:items-end"><Field label="销售覆盖价"><input type="number" min="0" step="0.01" value={sku.salePriceOverride??""} onChange={e=>set("salePriceOverride",e.target.value===""?null:Number(e.target.value))} placeholder={`使用仓库价 ¥${Number(sku.warehouseBasePrice??sku.basePrice).toFixed(2)}`} className="input"/></Field><button disabled={busy||sku.salePriceOverride===null||sku.salePriceOverride===undefined} onClick={()=>savePrice(sku)} className="rounded-xl bg-orange-500 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">保存销售价</button><button disabled={busy||sku.salePriceOverride===null||sku.salePriceOverride===undefined} onClick={()=>savePrice(sku,true)} className="rounded-xl border px-4 py-3 text-sm disabled:opacity-40">恢复仓库价</button></div>{sku.tiers.length>0&&<div className="mt-4"><p className="text-xs font-semibold text-slate-600">阶梯价（只读）</p>{sku.tiers.map((tier,index)=><p key={index} className="mt-2 flex justify-between rounded-lg bg-white px-3 py-2 text-xs text-slate-500"><span>{tier.minQty}{tier.maxQty?`-${tier.maxQty}`:" 件以上"}</span><b>¥{tier.unitPrice.toFixed(2)}/件</b></p>)}</div>}</div>;
 return <div className="rounded-xl bg-slate-50 p-4"><div className="grid gap-3 md:grid-cols-4"><Field label="SKU 编码"><input value={sku.skuCode} onChange={e=>set("skuCode",e.target.value)} className="input"/></Field><Field label="规格名称"><input value={sku.specName} onChange={e=>set("specName",e.target.value)} className="input"/></Field><Field label="基础价格"><input type="number" min="0" step="0.01" value={sku.basePrice} onChange={e=>set("basePrice",Number(e.target.value))} className="input"/></Field><Field label="库存"><input type="number" min="0" step="1" value={sku.stock} onChange={e=>set("stock",Number(e.target.value))} className="input"/></Field></div><div className="mt-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-slate-600">阶梯价</p><div className="flex gap-2"><button onClick={()=>set("tiers",[...sku.tiers,{minQty:1,maxQty:null,unitPrice:sku.basePrice}])} className="text-xs text-orange-600">+ 添加阶梯</button><button onClick={remove} className="text-xs text-red-500">删除规格</button></div></div>{sku.tiers.map((tier,index)=><div key={index} className="mt-2 grid grid-cols-1 gap-2 min-[420px]:grid-cols-[1fr_1fr_1fr_44px]"><input aria-label="起订量" type="number" min="1" value={tier.minQty} onChange={e=>set("tiers",sku.tiers.map((t,i)=>i===index?{...t,minQty:Number(e.target.value)}:t))} className="input" placeholder="起订量"/><input aria-label="截止量" type="number" min="1" value={tier.maxQty??""} onChange={e=>set("tiers",sku.tiers.map((t,i)=>i===index?{...t,maxQty:e.target.value?Number(e.target.value):null}:t))} className="input" placeholder="不限"/><input aria-label="阶梯单价" type="number" min="0" step="0.01" value={tier.unitPrice} onChange={e=>set("tiers",sku.tiers.map((t,i)=>i===index?{...t,unitPrice:Number(e.target.value)}:t))} className="input" placeholder="单价"/><button onClick={()=>set("tiers",sku.tiers.filter((_,i)=>i!==index))} className="rounded-lg bg-red-50 text-red-500"><Trash2 size={14} className="mx-auto"/></button></div>)}</div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-medium text-slate-600">{label}<div className="mt-2">{children}</div></label>}
