"use client";

import { FormEvent, useCallback, useEffect, useState, type ReactNode } from "react";
import type { ProviderCapabilities } from "../lib/contracts/pipeline";
import { apiErrorMessage, apiFetch, apiJson, asList } from "./api-client";
import { AlertIcon, SparkIcon } from "./icon";
import { LoadingBlock, Notice, StatusBadge } from "./ui";

type Provider = "deepseek" | "openai" | "openai_compatible";
type Profile = { id: string; name: string; provider: Provider; revision: number; active: boolean; hasPendingRevision?: boolean; config: { apiKeyConfigured?: boolean; apiKeyHint?: string | null; baseUrl?: string; model?: string; textModel?: string; modelsPath?: string; chatPath?: string; inputFormat?: string; allowedHosts?: string[]; timeoutMs?: number; maxTokens?: number; priceVersion?: string; promptPriceMinor?: number; completionPriceMinor?: number; currency?: string }; lastProbe?: ProviderCapabilities & { checkedAt?: string } };
const defaults = { name: "", provider: "deepseek" as Provider, baseUrl: "https://api.deepseek.com/v1", model: "", textModel: "", modelsPath: "/models", chatPath: "/chat/completions", inputFormat: "data_url", allowedHosts: "api.deepseek.com", timeoutMs: "60000", maxTokens: "1024", priceVersion: "", promptPriceMinor: "0", completionPriceMinor: "0", currency: "CNY", apiKey: "", clearApiKey: false };

export function AiProfileSettings() {
  const [profiles, setProfiles] = useState<Profile[]>([]), [selectedId, setSelectedId] = useState<string | null>(null), [form, setForm] = useState(defaults);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null), [success, setSuccess] = useState<string | null>(null);
  const choose = useCallback((profile: Profile) => { const c=profile.config||{}; setSelectedId(profile.id); setForm({name:profile.name,provider:profile.provider,baseUrl:c.baseUrl||"",model:c.model||"",textModel:c.textModel||"",modelsPath:c.modelsPath||"/models",chatPath:c.chatPath||"/chat/completions",inputFormat:c.inputFormat||"data_url",allowedHosts:(c.allowedHosts||[]).join(","),timeoutMs:String(c.timeoutMs??60000),maxTokens:String(c.maxTokens??1024),priceVersion:c.priceVersion||"",promptPriceMinor:String(c.promptPriceMinor??0),completionPriceMinor:String(c.completionPriceMinor??0),currency:c.currency||"CNY",apiKey:"",clearApiKey:false}); }, []);
  const load = useCallback(async () => { setLoading(true); try { const items=asList<Profile>(await apiFetch<unknown>("/api/v1/admin/ai-profiles",{cache:"no-store"}),["profiles","items","records"]); setProfiles(items); const current=items.find(i=>i.id===selectedId)||items.find(i=>i.active)||items[0]; if(current)choose(current); } catch(cause){setError(apiErrorMessage(cause));} finally{setLoading(false);} },[choose,selectedId]);
  useEffect(()=>{void load();},[load]);
  function createNew(provider:Provider="deepseek"){const preset=provider==="openai"?{baseUrl:"https://api.openai.com/v1",allowedHosts:"api.openai.com"}:provider==="deepseek"?{baseUrl:"https://api.deepseek.com/v1",allowedHosts:"api.deepseek.com"}:{baseUrl:"",allowedHosts:""};setSelectedId(null);setForm({...defaults,...preset,provider});setError(null);setSuccess(null);}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);setError(null);setSuccess(null);const integer=(v:string)=>v.trim()?Number(v):undefined;try{const payload={name:form.name.trim(),provider:form.provider,clearApiKey:form.clearApiKey,config:{baseUrl:form.baseUrl.trim()||undefined,model:form.model.trim()||undefined,textModel:form.textModel.trim()||undefined,modelsPath:form.modelsPath.trim()||undefined,chatPath:form.chatPath.trim()||undefined,inputFormat:form.inputFormat,allowedHosts:form.allowedHosts.split(",").map(i=>i.trim()).filter(Boolean),timeoutMs:integer(form.timeoutMs),maxTokens:integer(form.maxTokens),priceVersion:form.priceVersion.trim()||undefined,promptPriceMinor:integer(form.promptPriceMinor),completionPriceMinor:integer(form.completionPriceMinor),currency:form.currency.trim()||undefined,...(form.apiKey?{apiKey:form.apiKey}:{})}};const response=await apiJson<{profile?:Profile}>(selectedId?`/api/v1/admin/ai-profiles/${encodeURIComponent(selectedId)}`:"/api/v1/admin/ai-profiles",selectedId?"PUT":"POST",payload);if(response.profile)choose(response.profile);setSuccess(selectedId?"已生成新的不可变版本，旧任务不受影响。":"档案已创建，探测后可手动激活。");await load();}catch(cause){setError(apiErrorMessage(cause,"配置未保存"));}finally{setBusy(false);}}
  async function run(action:"probe"|"activate"|"copy"|"delete"){if(!selectedId)return;if(action==="delete"&&!window.confirm("确认删除这个未激活的配置档案？"))return;if(action==="activate"&&!window.confirm("激活后仅影响之后创建的新任务，确认继续？"))return;setBusy(true);setError(null);setSuccess(null);try{if(action==="delete")await apiJson(`/api/v1/admin/ai-profiles/${encodeURIComponent(selectedId)}`,"DELETE");else if(action==="copy")await apiJson(`/api/v1/admin/ai-profiles/${encodeURIComponent(selectedId)}/copy`,"POST",{});else{const result=await apiJson<ProviderCapabilities>(`/api/v1/admin/ai-profiles/${encodeURIComponent(selectedId)}/${action}`,"POST",{});if(action==="probe"&&!(result.available&&result.vision)){setError(result.reason||"探测未通过，档案不会自动激活。");await load();return;}}setSuccess(action==="probe"?"探测完成；探测不会自动激活配置。":action==="activate"?"配置已激活，只影响之后创建的任务。":action==="copy"?"已复制为新档案。":"档案已删除。");if(action==="delete")createNew();await load();}catch(cause){setError(apiErrorMessage(cause,"操作失败"));}finally{setBusy(false);}}
  if(loading)return <section className="card"><LoadingBlock label="正在读取 AI 配置…"/></section>;
  const selected=profiles.find(i=>i.id===selectedId);
  return <div className="ai-profile-layout"><section className="card"><div className="card-header"><div><h2>模型档案</h2><p>激活配置只用于之后创建的任务</p></div><button className="button button-primary" type="button" onClick={()=>createNew()}>新建</button></div><div className="card-body"><div className="ai-profile-list">{profiles.map(p=><button type="button" key={p.id} className={`ai-profile-item${p.id===selectedId?" ai-profile-item-active":""}`} onClick={()=>choose(p)}><span><strong>{p.name}</strong><small>{p.provider==="openai_compatible"?"自定义":p.provider} · v{p.revision}</small></span>{p.active&&<StatusBadge status="published" label={p.hasPendingRevision?"旧版生效中":"已激活"}/>}</button>)}</div></div></section><section className="card"><div className="card-header"><div><h2>{selectedId?"编辑配置档案":"创建配置档案"}</h2><p>API Key 留空保持不变，清除必须明确勾选</p></div><SparkIcon size={18}/></div><div className="card-body">{error&&<Notice tone="danger"><AlertIcon size={15}/>{error}</Notice>}{success&&<Notice tone="success">{success}</Notice>}<form className="form-grid" onSubmit={save}><div className="form-grid form-grid-2">
    <Field label="档案名称"><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><Field label="供应商"><select className="select" value={form.provider} onChange={e=>createNew(e.target.value as Provider)}><option value="deepseek">DeepSeek</option><option value="openai">OpenAI</option><option value="openai_compatible">自定义兼容接口</option></select></Field>
    <Field label="Base URL"><input className="input" type="url" value={form.baseUrl} onChange={e=>setForm({...form,baseUrl:e.target.value})} required/></Field><Field label="视觉模型"><input className="input" value={form.model} onChange={e=>setForm({...form,model:e.target.value})} required/></Field><Field label="文本模型"><input className="input" value={form.textModel} onChange={e=>setForm({...form,textModel:e.target.value})}/></Field><Field label="输入格式"><select className="select" value={form.inputFormat} onChange={e=>setForm({...form,inputFormat:e.target.value})}><option value="data_url">Data URL</option><option value="image_url">image_url</option><option value="bytes">字节对象</option><option value="base64">Base64</option></select></Field>
    <Field label="能力路径"><input className="input" value={form.modelsPath} onChange={e=>setForm({...form,modelsPath:e.target.value})}/></Field><Field label="对话路径"><input className="input" value={form.chatPath} onChange={e=>setForm({...form,chatPath:e.target.value})}/></Field><Field label="允许主机"><input className="input" value={form.allowedHosts} onChange={e=>setForm({...form,allowedHosts:e.target.value})} placeholder="逗号分隔"/></Field><Field label="API Key"><input className="input" type="password" autoComplete="new-password" value={form.apiKey} onChange={e=>setForm({...form,apiKey:e.target.value,clearApiKey:false})} placeholder={selected?.config.apiKeyConfigured?`已配置 ${selected.config.apiKeyHint||"（已脱敏）"}`:"尚未配置"}/><label className="check-row"><input type="checkbox" checked={form.clearApiKey} onChange={e=>setForm({...form,clearApiKey:e.target.checked,apiKey:""})}/>明确清除密钥</label></Field>
    <Field label="超时（毫秒）"><input className="input" type="number" min="1000" max="600000" value={form.timeoutMs} onChange={e=>setForm({...form,timeoutMs:e.target.value})}/></Field><Field label="最大输出 token"><input className="input" type="number" min="1" max="1000000" value={form.maxTokens} onChange={e=>setForm({...form,maxTokens:e.target.value})}/></Field><Field label="价格版本"><input className="input" value={form.priceVersion} onChange={e=>setForm({...form,priceVersion:e.target.value})}/></Field><Field label="币种"><input className="input" maxLength={3} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})}/></Field><Field label="输入价（整数单位/token）"><input className="input" type="number" min="0" value={form.promptPriceMinor} onChange={e=>setForm({...form,promptPriceMinor:e.target.value})}/></Field><Field label="输出价（整数单位/token）"><input className="input" type="number" min="0" value={form.completionPriceMinor} onChange={e=>setForm({...form,completionPriceMinor:e.target.value})}/></Field>
  </div><div className="section-actions"><button className="button button-primary" type="submit" disabled={busy}>{selectedId?"保存新版本":"创建档案"}</button>{selectedId&&<><button className="button button-secondary" type="button" onClick={()=>void run("probe")} disabled={busy}>探测</button><button className="button button-secondary" type="button" onClick={()=>void run("activate")} disabled={busy||(selected?.active&&!selected?.hasPendingRevision)}>激活</button><button className="button button-quiet" type="button" onClick={()=>void run("copy")} disabled={busy}>复制</button><button className="button button-danger" type="button" onClick={()=>void run("delete")} disabled={busy||selected?.active}>删除</button></>}</div></form></div></section></div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="field"><label>{label}</label>{children}</div>;}
