import { createHash, createHmac, timingSafeEqual } from 'node:crypto';
import { getDb } from './db';

const WINDOW_MS=5*60_000;
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
function secret(){const value=process.env.INTEGRATION_SHARED_SECRET?.trim();if(!value||value.length<32)throw new Error('INTEGRATION_SHARED_SECRET is not configured');return value;}
function canonical(method:string,path:string,body:string,timestamp:string,nonce:string){return `${timestamp}.${nonce}.${method.toUpperCase()}.${path}.${hash(body)}`;}
export function integrationHeaders(method:string,path:string,body:string,nonce:string){const timestamp=String(Date.now());return {'content-type':'application/json','x-integration-timestamp':timestamp,'x-integration-nonce':nonce,'x-integration-signature':createHmac('sha256',secret()).update(canonical(method,path,body,timestamp,nonce)).digest('hex')};}
export function verifyIntegrationRequest(request:Request,body:string){const timestamp=request.headers.get('x-integration-timestamp')||'',nonce=request.headers.get('x-integration-nonce')||'',supplied=request.headers.get('x-integration-signature')||'',time=Number(timestamp);if(!/^[A-Za-z0-9_-]{8,160}$/.test(nonce)||!Number.isFinite(time)||Math.abs(Date.now()-time)>WINDOW_MS||!/^[a-f0-9]{64}$/.test(supplied))return false;const pathname=new URL(request.url).pathname,basePath=(process.env.NEXT_PUBLIC_BASE_PATH||'/warehouse').replace(/\/$/,'');const candidates=[pathname,...(!pathname.startsWith(`${basePath}/`)?[`${basePath}${pathname}`]:[])];const valid=candidates.some(path=>{const expected=createHmac('sha256',secret()).update(canonical(request.method,path,body,timestamp,nonce)).digest('hex');return timingSafeEqual(Buffer.from(expected),Buffer.from(supplied));});if(!valid)return false;const db=getDb();db.exec(`CREATE TABLE IF NOT EXISTS integration_nonces(nonce TEXT PRIMARY KEY,expires_at TEXT NOT NULL,created_at TEXT NOT NULL)`);try{db.transaction(()=>{db.prepare('DELETE FROM integration_nonces WHERE expires_at<=?').run(new Date().toISOString());db.prepare('INSERT INTO integration_nonces VALUES(?,?,?)').run(nonce,new Date(Date.now()+WINDOW_MS).toISOString(),new Date().toISOString());})();return true;}catch{return false;}}
